apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: statsd-agent
  name: statsd-agent
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: statsd-agent
    spec:
      containers:
      - image: davarski/chapter7k8s_statsd-agent:latest
        name: simplebank-statsd-agent
        ports:
        - containerPort: 8125
        resources: {}
      restartPolicy: Always
status: {}
